# Fly.io configuration file for bgcatalog
app = "bgcatalog"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "bgcatalog_project.settings"
  PYTHONUNBUFFERED = "1"
  PORT = "8000"

[experimental]
  auto_rollback = true

# Configuração de VM para plano gratuito
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# HTTP service
[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"