# Fly.io configuration file for bgcatalog
app = "bgcatalog"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "bgcatalog_project.settings"
  PYTHONUNBUFFERED = "1"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"