# Generated by Django 5.2.7 on 2025-10-13 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(blank=True, help_text='BoardGameGeek ID', null=True, unique=True)),
                ('name', models.CharField(help_text='Game name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Game description')),
                ('year_published', models.IntegerField(blank=True, help_text='Year published', null=True)),
                ('designer', models.CharField(blank=True, help_text='Game designer(s)', max_length=255)),
                ('min_players', models.IntegerField(blank=True, help_text='Minimum players', null=True)),
                ('max_players', models.IntegerField(blank=True, help_text='Maximum players', null=True)),
                ('min_playtime', models.IntegerField(blank=True, help_text='Minimum playtime (minutes)', null=True)),
                ('max_playtime', models.IntegerField(blank=True, help_text='Maximum playtime (minutes)', null=True)),
                ('min_age', models.IntegerField(blank=True, help_text='Minimum age', null=True)),
                ('msrp_price', models.DecimalField(blank=True, decimal_places=2, help_text="Manufacturer's Suggested Retail Price (MSRP)", max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('damaged', 'Damaged'), ('missing_pieces', 'Missing Pieces')], default='new', help_text='Game condition', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final price after discount', max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=1, help_text='Available quantity in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_sold', models.BooleanField(default=False, help_text='Mark as sold')),
                ('sold_date', models.DateTimeField(blank=True, help_text='Date when sold', null=True)),
                ('images_urls', models.TextField(blank=True, help_text='JSON array of image URLs')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Main thumbnail URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the game')),
            ],
            options={
                'verbose_name': 'Board Game',
                'verbose_name_plural': 'Board Games',
                'ordering': ['-created_at'],
            },
        ),
    ]
