# Generated by Django 5.2.7 on 2025-11-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Game name', max_length=255)),
                ('bgg_id', models.CharField(blank=True, help_text="BoardGameGeek ID or BGA ID (prefixed with 'bga_')", max_length=50, null=True, unique=True)),
                ('year_published', models.IntegerField(blank=True, help_text='Year published', null=True)),
                ('designer', models.CharField(blank=True, help_text='Game designer(s)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Game description')),
                ('image_url', models.URLField(blank=True, help_text='Full-size image URL', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL', max_length=500)),
                ('min_players', models.IntegerField(blank=True, help_text='Minimum number of players', null=True)),
                ('max_players', models.IntegerField(blank=True, help_text='Maximum number of players', null=True)),
                ('min_playtime', models.IntegerField(blank=True, help_text='Minimum playtime (minutes)', null=True)),
                ('max_playtime', models.IntegerField(blank=True, help_text='Maximum playtime (minutes)', null=True)),
                ('min_age', models.IntegerField(blank=True, help_text='Minimum recommended age', null=True)),
                ('categories', models.CharField(blank=True, help_text='Comma-separated categories', max_length=500)),
                ('mechanics', models.CharField(blank=True, help_text='Comma-separated mechanics', max_length=500)),
                ('rating_average', models.FloatField(blank=True, help_text='Average user rating', null=True)),
                ('rating_bayes', models.FloatField(blank=True, help_text='Bayes average rating', null=True)),
                ('rank_overall', models.IntegerField(blank=True, help_text='Overall BGG rank', null=True)),
                ('num_ratings', models.IntegerField(blank=True, help_text='Number of ratings', null=True)),
                ('msrp_price', models.DecimalField(blank=True, decimal_places=2, help_text='MSRP price in EUR', max_digits=10, null=True)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage (0-100)')),
                ('stock_quantity', models.IntegerField(default=1, help_text='Available stock quantity')),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('very_good', 'Very Good'), ('good', 'Good'), ('acceptable', 'Acceptable')], default='new', help_text='Game condition', max_length=20)),
                ('is_sold', models.BooleanField(default=False, help_text='Mark as sold')),
                ('sold_date', models.DateTimeField(blank=True, help_text='Date sold', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bgg_id'], name='catalog_boa_bgg_id_a1c1de_idx'), models.Index(fields=['name'], name='catalog_boa_name_68d2c1_idx'), models.Index(fields=['created_at'], name='catalog_boa_created_236885_idx'), models.Index(fields=['is_sold'], name='catalog_boa_is_sold_34df02_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Reserved quantity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Reservation status', max_length=20)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=255)),
                ('customer_email', models.EmailField(help_text='Customer email', max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone', max_length=50)),
                ('session_key', models.CharField(help_text='Session key', max_length=255)),
                ('reserved_at', models.DateTimeField(auto_now_add=True, help_text='Reservation created')),
                ('expires_at', models.DateTimeField(help_text='Reservation expires')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Sale confirmed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Reservation cancelled', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes')),
                ('game', models.ForeignKey(help_text='Reserved game', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.boardgame')),
            ],
            options={
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='catalog_sto_status_a1027a_idx'), models.Index(fields=['session_key'], name='catalog_sto_session_705cbf_idx'), models.Index(fields=['game', 'status'], name='catalog_sto_game_id_e48939_idx')],
            },
        ),
    ]
