# Generated by Django 5.2.7 on 2025-10-23 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Reserved quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed Sale'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=255)),
                ('customer_email', models.EmailField(help_text='Customer email', max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone', max_length=50)),
                ('customer_message', models.TextField(blank=True, help_text='Customer message')),
                ('session_key', models.CharField(help_text='Session ID', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When reservation was created')),
                ('expires_at', models.DateTimeField(help_text='When reservation expires')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When sale was confirmed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this reservation')),
                ('game', models.ForeignKey(help_text='Reserved game', on_delete=django.db.models.deletion.CASCADE, to='catalog.boardgame')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
