name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main, creation ]
  pull_request:
    branches: [ main, creation ]

jobs:
  build-apk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache buildozer global
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/*.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
          sudo apt-get install -y libncurses6 libncurses-dev libstdc++6 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev
          sudo apt-get install -y autoconf libtool pkg-config

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install buildozer cython

      - name: Initialize buildozer
        run: |
          buildozer android clean || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
          if-no-files-found: warn
