name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main, creation ]
  pull_request:
    branches: [ main, creation ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip

      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK with buildozer
        run: |
          # Build with all licenses pre-accepted
          yes | buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bgcatalog-apk
          path: bin/*.apk
