name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install buildozer requirements
        run: |
          sudo apt-get install -y libncurses6 libncurses-dev libstdc++6 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
