name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches: [ main, creation ]
  pull_request:
    branches: [ main, creation ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip

      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android licenses first
        run: |
          # Create directory for licenses
          mkdir -p ~/.android/
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/repositories.cfg
          # Set environment variables
          export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
          export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk

      - name: Build APK with buildozer
        run: |
          # Build the APK with auto-accept licenses
          echo "y" | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bgcatalog-apk
          path: bin/*.apk
