name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, creation ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: true

      - name: Install Cordova
        run: |
          npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create bgcatalog-app org.example.bgcatalog BGCatalog
          cd bgcatalog-app
          cordova platform add android

      - name: Create app content
        run: |
          cd bgcatalog-app/www
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>BGCatalog</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      margin: 0;
                      padding: 20px;
                      background-color: #f5f5f5;
                  }
                  .container {
                      max-width: 400px;
                      margin: 0 auto;
                      background: white;
                      padding: 20px;
                      border-radius: 10px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  h1 {
                      text-align: center;
                      color: #333;
                      margin-bottom: 30px;
                  }
                  .feature {
                      padding: 15px;
                      margin: 10px 0;
                      background: #e8f4fd;
                      border-radius: 5px;
                      border-left: 4px solid #2196F3;
                  }
                  button {
                      width: 100%;
                      padding: 15px;
                      background: #2196F3;
                      color: white;
                      border: none;
                      border-radius: 5px;
                      font-size: 16px;
                      margin: 10px 0;
                      cursor: pointer;
                  }
                  button:hover {
                      background: #1976D2;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🎲 BGCatalog</h1>
                  <p style="text-align: center; color: #666;">Board Game Catalog App</p>
                  
                  <div class="feature">
                      <h3>📱 Mobile Ready</h3>
                      <p>App instalado com sucesso no seu dispositivo!</p>
                  </div>
                  
                  <div class="feature">
                      <h3>🎯 Funcionalidades</h3>
                      <p>• Catalogar jogos<br>• Barcode scanner<br>• Export/Import<br>• Inventário</p>
                  </div>
                  
                  <button onclick="alert('BGCatalog funcionando!')">Testar App</button>
                  <button onclick="window.location.href='tel:+5511999999999'">Contato</button>
              </div>
              
              <script>
                  document.addEventListener('deviceready', function() {
                      console.log('Cordova is ready');
                  }, false);
              </script>
          </body>
          </html>
          EOF

      - name: Build APK
        run: |
          cd bgcatalog-app
          cordova build android --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: "bgcatalog-app/platforms/android/app/build/outputs/apk/release/*.apk"
          if-no-files-found: warn
